### ISSUE TITLE
Creating a Profile Page for Android

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#133]
As the title indicates, we need to create a profile page for Android .

**Comment by haozturk** [comment]
I have created a branch dedicated to this purpose and made a dummy profile page. Here is the branch: https://github.com/bounswe/bounswe2019group5/tree/android_issue133_profilePage

**Comment by haozturk** [comment]
A dummy profile page is created. Currently system only supports viewing users' own profile. We should also support viewing others' profile as the project proceed.

**Comment by furkan-kadioglu** [comment]
Who is the reviewer for this page? I don't see any pr for this task. if it is completed then you should update status.

**Comment by mstniy** [comment]
The profile page is functional now, except for the two buttons, "View Comments" and "View Attended Languages". I can't see a requirement saying that the user should be able to see his attended languages, so that button can be removed. Regarding the "view comments" button, I will be opening a seperate issue, as this one is pretty old and crowded.
