### ISSUE TITLE
Android Theme Choice

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#151]
I think it is important to choose a theme for our Android app. In the simplest case we can choose one or two colors for our app which dominates the background. For instance, when you think of Spotify, black and green comes to your mind. We should also have a similar theme in order to have a visual characteristic. Any ideas are welcome

**Comment by ali-deser-2016400261** [comment]
Totally agreed, I think it is a necessary issue because of the fact that we are working on our issues seperately and besides the coding conflicts, I suppose design conflicts are crucial for our app too.

We can also advise the front-end team to come with something corrolated together.
My own idea is that we can mainly work with color tones like Blue, Green or together with (Turquoise) and Violet. These comes with a good visuality for presentations and also attractive for users (We can say that colors bind users to the app)

**Comment by Melteos** [comment]
We as the frontend theme also talked about our color choices and themes, we also think that android and web should be compatible as themes. You can look at the website to adapt the theme of the Android, or you can give feedback to us about changing the theme. http://52.14.169.152:3000/
Looking forward to your thoughts.

**Comment by furkan-kadioglu** [comment]
I cannot consistency and user friendly design in frontend at now, and mobile is consistent in itself but frontend and android team have to plan a meeting for this.

**Comment by haozturk** [comment]
We can discuss this issue if we have a general meeting in this week, otherwise I think we can a chat on this on Tuesday(19.11.2019) after the class with mobile and web teams. I am open for other suggestions as well.

**Comment by ali-deser-2016400261** [comment]
I guess the design is completed,and no further changes will be made related with this.Thus, closing this issue
