### ISSUE TITLE
Android app progress tracking

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#260]
The user should be able to see his progress.

**Comment by ali-deser-2016400261** [comment]
I've made  a talk with front end about the *Progress* issue namely. Yet, we have figured out that there is no such info since we don't know the information like 
- How many exercise exist in a level (A1,A2,B1,B2,C1,C2)
- How many total exercise  exist in the system.

We need the informations above to calculate the progress of a certain user

**Comment by ali-deser-2016400261** [comment]
done with the last PR

**Comment by mstniy** [comment]
Solved by PR #337
