### ISSUE TITLE
Use case meeting 

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#29]

**Comment by Melteos** [comment]
**updating with respect to feedback.**

1. - [ ] A use case “extends” an actor? Is it possible :) ? There should be arrows from actors to the use cases, without any relation type such as extends or includes. 

2. - [ ] For searching, you designed as “advanced search” includes “search by tag” or “search by topic”… Are they all included in advanced search, or they are just options of advanced searching? I think it would better to use “extends” instead of “include”. 

3. - [ ] Is “Recommend Expert” a use case? It is a functionality carried out by not an end-user, but the system itself.  ;delete this;

4. - [ ] What about use cases about tracking the progress?(profile page extention)

5. - [ ] Similarly, you need to **add** related use case(s) about the proficiency exam for determining the level. 

6. - [ ] “Search user” and “search expert” use cases seem duplicate to me. You can use just one of them for several scenarios.  (delete search expert and find expert just leave include recommend expert)

7. - [ ] Sending essay may extend finding an expert.  ( Writing will be modified a lot. Writing goes to chat and essay, and then requests and .. )

8. - [ ] Instead of connecting everything as a flow diagram, you can directly connect some use cases to the actors. For example, annotation may be connected to the actor, and this use case may be extended by “annotate text”, “annotate image” etc. The use case diagram should not be considered as a sequence of operations, it is just the use cases that are possible to be carried out by an end-user.

**Comment by abdullah-oncu-2015400237** [comment]
For 3. I didn't delete, because recommendation page is another use case but I changed it from recommend expert to recommend expert page.

**Comment by abdullah-oncu-2015400237** [comment]
I understand from 6. we shouldn't implement detailed things, it means if I added search user somewhere, no need to add it another place as an optional thing.

**Comment by abdullah-oncu-2015400237** [comment]
I almost completed it, however there may some deficiencies about 7. and 8.

**Comment by Melteos** [comment]
> For 3. I didn't delete, because recommendation page is another use case but I changed it from recommend expert to recommend expert page.
i think they meant to say recommending experts is not something that a user does or have a choice in it, system does this automatically so there is no need to put it in use case diagram. Also they said that we shouldn't think of the use case as a flow diagram(what the user has to do in order to achieve something)
