### ISSUE TITLE
User search result design

### ISSUE THREAD

**Issue by muzunpostalci** [bounswe/bounswe2019group5#293]
I have implemented user search at #292.

![image](https://user-images.githubusercontent.com/32355922/69481715-a2bb0b00-0e24-11ea-8ded-13f016e33103.png)

It works flawless but the design of search result is not great. I will try to display search results in a better way so any suggestions are welcome.

**Comment by haozturk** [comment]
I can suggest putting a profile icon for each search result, so that the user can understand, he/she can navigate to the profile page by clicking it.

Moreover, let me ask you if the scrolling works or not in the current design. I could not find a query where the system finds many results, so that they do not fit the screen. If it works, then great! If not, we can improve that aspect.

**Comment by muzunpostalci** [comment]
Created pull request #332 with suggested modification.

**Comment by muzunpostalci** [comment]
Created pull request #332 with suggested modification.

**Comment by mstniy** [comment]
Solved by #332
