### ISSUE TITLE
Sequence Diagram - Exercises

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#34]
Exercise Sequence Diagram will be created in the meeting will be handled 
15.03.2019  11.00-13.00

**Comment by Melteos** [comment]
**updating with respect to feedback.**

- [ ] As an example of a common mistake, in the first sequence diagram about “Exercise”, there is a message getLanguageId sent to the Language class. However, this method signature is not available in the class diagram?

- [ ] In the same sequence diagram, if showResult() is a method, it should not be represented as dashed line. 
(instead of a method you can just say Show results like a comment (there are examples in the other diagrams) )

**Comment by ali-deser-2016400261** [comment]
Handled
