### ISSUE TITLE
Sequence Diagram - Report

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2019group5#37]
We design sequence diagram for reporting a user and update the class diagram accordingly.

Review Needed ASAP!

**Comment by Melteos** [comment]
**updating with respect to feedback.**

- [ ] Similarly, in 4th and 5th sequence diagrams, actually multiple use cases are discussed. For example, in the 5th one about reporting, reporting a user through chat, or through writing exercises are separate cases. Additionally, banning a user, evaluating reports etc. should not be included in “reporting” sequence diagram, since they are definitely distinct use cases, even though related. Shortly, you may decompose these 2 diagrams into at least 4-5 diagrams :)
(there will be 3 seperate cases: user reporting through chat, through writing and admin banning.)

**Comment by Melteos** [comment]
i seperated admin dealing with reports 
https://www.lucidchart.com/documents/edit/b68063ac-29bd-4193-b818-66da5caba47d/0

User Reporting Another User In Chat
https://www.lucidchart.com/documents/edit/7307e3ee-eb7c-4930-8474-b961005a8003/0?shared=true&

**Comment by multiminparvo** [comment]
User Reporting Another User from Witing Channel

https://www.lucidchart.com/invitations/accept/a47b4051-d558-4927-b451-b623c9845324
