### ISSUE TITLE
Sequence Diagram- Searching

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2019group5#39]
Invitation Link: https://www.lucidchart.com/invitations/accept/c1183988-756c-4bf3-a462-dace86c09348

We need to design a sequence diagram for searching cases.

There are three cases we need to consider : 
-Semantic search
-Profile search
-Advanced search

**Comment by ymBila** [comment]
reviwed and updated

**Comment by Melteos** [comment]
**updating with respect to feedback.**

- [ ] In the 4th sequence diagram of searching, the results may be collected within a for loop, then the result list may be shown to the end-user. 
(collecting the results in a for loop)

- [ ] Similarly, in 4th and 5th sequence diagrams, actually multiple use cases are discussed. For example, in the 5th one about reporting, reporting a user through chat, or through writing exercises are separate cases. Additionally, banning a user, evaluating reports etc. should not be included in “reporting” sequence diagram, since they are definitely distinct use cases, even though related. Shortly, you may decompose these 2 diagrams into at least 4-5 diagrams :)

**Comment by uskudarli** [comment]
If you provide descriptions of tasks and links to relevant material, it may make your life much easier.

**Comment by multiminparvo** [comment]
Semantic Search : https://www.lucidchart.com/invitations/accept/407087d4-6dfb-441b-8023-c2f3fe04029d

Advanced Search: https://www.lucidchart.com/invitations/accept/e98b31de-bb01-4e16-887f-4766217d562c

Profile Search :  https://www.lucidchart.com/invitations/accept/c709457e-f0c7-45a7-a745-dfe6b344aacd
