### ISSUE TITLE
Agenda for meeting 9

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#52]
This issue is for determining our agenda for next meeting( 10 April, Wednesday ).
Everyone feel free to add the topics we should discuss. 🎆 ✨

**Comment by multiminparvo** [comment]
_Since there isn't any homework at that moment, we can review our project plan according to our lecturer's advices_

Dear Students,
Please do NOT use spreadsheets -- you will recall that we specifically discussed the difficulties associated with using spreadsheets in terms of tracking. This requires a knowledgeable project management person constantly maintaining a spreadsheet. There is an allure to using them, since people are very familiar with spreadsheets and easy to prepare, but for tracking they are not effective.

 

In class I informed you about Project Libre -- it is in the resources section in Piazza you can find -- this is a tool created for project planning. OpenProject is a heftier solution, but also very acceptable

Also, do NOT choose trial/demo/properietary versions -- as their use is not sustainable in the context of our education life. You will be able to transfer what you learn to proprietary tools in the future. 

 

Recall the goal of project planning is to:

 

define activities
define tasks
estimate durations
allocate resources
define milestones
track  progress

**Comment by furkan-kadioglu** [comment]
Discussion about software tools.
